apiVersion: apps/v1
kind: Deployment
metadata:
  name: tecnospeed-deployment
spec:
  selector:
    matchLabels:
      app: tecnospeed
  replicas: 1
  template:
    metadata:
      labels:
        app: tecnospeed
    spec:
      containers:
      - name: tecnospeed
    # enter the path to your image, be sure to include the correct region prefix    
        image: iad.ocir.io/id4beafwqb9e/cristianohoshikawa/tecnospeed:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
    # enter the name of the secret you created  
      - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: tecnospeed-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tecnospeed
